### ISSUE TITLE
documentation does not explain how to configure TLS

### ISSUE THREAD

**Issue by rob-nicholson** [ibm-cloud-docs/cloud-pak-integration#1]
The documentation does not explain the steps necessary to configure TLS so that the user does not see certificate errors when accessing the platform navigator. 

I believe that this can be done by using the navTLSSecret setting and obtaining a certificate that authenticates the domain that the cluster is running on but the steps to do this are not explained.

**Comment by Jamstah** [comment]
There is no `navTLSSecret` setting any more. TLS is provided by the services using the default openshift app domain certificates. Closing this.
